proxmox_secrets:
    api_user: ENC[AES256_GCM,data:ozBaF2Y1Rjk=,iv:M0ezPyKUM0jy0h+prrFtH3cV8RnZ9tkcjUtXEwtnyfE=,tag:DzuJ9kxEyiyRBvb3S/mY4Q==,type:str]
    api_token_id: ENC[AES256_GCM,data:RFylfzyBnA==,iv:oECBm/s/pydMLWkxBVlJPBjcLzNgb98fxICdYv+7qz0=,tag:GZVCDXlVIN1k1njUVSJ9Qg==,type:str]
    api_token_secret: ENC[AES256_GCM,data:/Ov8gaZT+QT5lvl/segw1Dcyc53ReWw=,iv:G0+OEXO+uvzjW1ykr5p4MxqbkpAqgKeUPDTevMzudjI=,tag:56om3bRiiQsoYGL6+yVg7Q==,type:str]
acme:
    email: ENC[AES256_GCM,data:Lgpc5el00jXzblNzeIeLTi3R9g==,iv:XXpEvMEDdWP5gPqJRj5pGWJTm8keRZFDNyKbX3vtymc=,tag:YK2xCWVPFNxyAAuxh+pp/Q==,type:str]
    domain: ENC[AES256_GCM,data:thMGDx+7W2M=,iv:GPEjitVcmixm674bLiy8y0jarGSiSi4YLisGA9vahFI=,tag:+INx6SQ1VOTacmMFIyPUJA==,type:str]
    provider: ENC[AES256_GCM,data:evbJTgJc,iv:Jh353YplZqp7ahVgJV5zbAMBCuMyX2Yug4vGCUt12dE=,tag:c7HMObsEfCzcuBqKAuKbuw==,type:str]
    cf_token: ENC[AES256_GCM,data:yv348rhRUwx+sFZgGLRYM6tXJ60OYiDfL+JbQj7bn/2jhPCQL3mnWg==,iv:Jjgk3kAj2lpnqoEl/VQjkNGT+fVdeLi8iCZ5QySXbHA=,tag:uV/36pw0Hj8YMLD6w+8TJA==,type:str]
    cf_account_id: ENC[AES256_GCM,data:07Oc8tk58HzjzPR1ahfFdfKGBY+G/SL3rYr+Ehcvmlo=,iv:Q3ke8Bcig1jH5MbAU/R5apLUwVbKoCMYqt6499w0X/w=,tag:CRkiGCQcjitUOtDCQWJt2A==,type:str]
    cf_zone_id: ENC[AES256_GCM,data:zUd5qjZ2QuT06VxYLCUzeQcezO0kvlUl03iy6HzafKw=,iv:uHn813BJztGiBX1EJy3o1v/pTt+SCS95+75AFKMupio=,tag:x/TzTsskXlTdkM/95dCRog==,type:str]
sops:
    age:
        - recipient: age15wr79l0v753jpsz0fas0xnavwqucc4sglq4mdx8dssct5g97md6qeslr6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZGpBb2xqWm5SYkRBU2dM
            eVA3UStrL1BCMzB2b0NlaU1IVFpJUDc0YlhjCms5aWx1N0tIcWVNNWI5RlVuZmMv
            Z2dnTmpuVWZDZVE4NFJkcmFlOUU3L2cKLS0tIFhkYkZ2VnBPNDVuZXBTaE5tRnRT
            d2RrZ1hZcm9wTVFBZSt4bzVRTmJudHcK6o37HkPvCbL3DW8PQgjclmJVE+RryIMX
            rb85aQtTbGqkVV0qzD1GbBQr5hxleBrbGgkxXno0haCMMtLQil3tDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T19:28:50Z"
    mac: ENC[AES256_GCM,data:PBEOmiDRK+DGChnMTWCwDiCGHPVX0uFH0ZBQ1QuEyTdeL3HbpvzMq6qTgPI++g8KoFrafCaX3uFMUc8D3i/au/NdpzmEzRE5x+tzWSWnBTwS9zFVBsJ3Y8jZpmXojJgWGSnxpTofquWVxaof9JZWmiGIdBEMh6q4LpBkOT9CoNs=,iv:qIEraO8jTnYqwbmp9qLd2dNM7187RcLkuzgiQrGkG5M=,tag:r6Pf/pjIPU4Lwz8W/uJXFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
