---
ansible_python_interpreter: /usr/bin/python3

upgrade_system: false

proxmox:
  timezone: Europe/Vienna

  base_packages:
    - vim
    - htop
    - git
    - fastfetch

metrics_server:
  # otel collector on pve-rack1, pushed to victoriametrics on pve-rack1
  host: "192.168.1.221"
  port: 4318
  name: "otelcol"
