acme:
    name: letsencrypt-production
    contact_secret: ENC[AES256_GCM,data:AG8XpprFMCQ9rEe+6PC4JMtmAA==,iv:ojccVrO4qVNMp5VyyGLXZDY32aH9MEqO/p/pzll3N2s=,tag:h5Yu+RGDIJSpYiuS5/7AcQ==,type:str]
    directory: https://acme-v02.api.letsencrypt.org/directory
    dns:
        plugin: cloudflare
        api: cf
        cf_token_secret: ENC[AES256_GCM,data:2XoCgbMGnJLKmycSvIktEXHmN3ru8t98NHCLfRnJ6bjb1h0vDrBYiQ==,iv:lelWM69b43gDSRrxRmWlkbqqH1U8BEeKI+j8exAkV9g=,tag:dHjDYwn5QA+EjZ0H0ZvbhA==,type:str]
        cf_account_id_secret: ENC[AES256_GCM,data:g5EDxGD1kMpBnC47MW1VBkCJS5Eos8GmxY9+7BRgB5c=,iv:zK5Es4Q3nUAIuDS0LMjdFQ4FfD6qCvVpi8lOC+r+Bwg=,tag:9DGOQljnsNdj/cbDqXazkw==,type:str]
        cf_zone_id_secret: ENC[AES256_GCM,data:1RQfgSuM3SL5n5JrrQ88sIunIahlSbepRRHplJOfsnM=,iv:TqpCt3D6t+s5oNvQAFKTEJlr/SkejN7xiXRlKiby8fU=,tag:swbQVTh0v7aYtNQXo0xtEQ==,type:str]
sops:
    age:
        - recipient: age15wr79l0v753jpsz0fas0xnavwqucc4sglq4mdx8dssct5g97md6qeslr6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVEl1Zmk1TmVsYWxMZmJw
            WFFsdEsrMDkrbGVFcmVFMU9zSUs3YmRpUjJrCmkveW9NbE9YNlhQMjBZcGFHWGd5
            cTltOHhxSGt1bTE5cHhkZXp0ZDl2WjAKLS0tIEpTVGJrTmlzdXNYN0xkbnJqekh1
            VDFpS1o3SlFEVkhqU3J2YzRaUURpZzgK3oMXgRWCPI7SJhfiyOcOnhg6bI+w1n9B
            Yq3XXm1T7nS3j/sQSPuU77PJYGPFvs4zCwhd62vzULlxocs1ZCMIAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T14:51:43Z"
    mac: ENC[AES256_GCM,data:b+k6jnTLVggOZN9p99D9w+jht/tnVSsvrXZQgZdgXnj2Fl8j49cznodYVqXLCxV2xo1p16nDymVNY9udIxeNr/mjF+tgdGAwlK5npVLoROOeo/bfezguwyhFPxB7ghPgFxgO2McqDtDPMmDPjfAU0jKMlUfa3Z24uFjZYrXNF30=,iv:vIO9nVdsoA2k5vKXxGa7iSxfLNKcbePayTlOiB8kdvA=,tag:yziqkuDJoi5hwgoNhAbKqg==,type:str]
    encrypted_regex: ^.*(api_token|password|secret|token).*$
    version: 3.11.0
