acme:
    name: letsencrypt-production
    contact_secret: ENC[AES256_GCM,data:AG8XpprFMCQ9rEe+6PC4JMtmAA==,iv:ojccVrO4qVNMp5VyyGLXZDY32aH9MEqO/p/pzll3N2s=,tag:h5Yu+RGDIJSpYiuS5/7AcQ==,type:str]
    directory: https://acme-v02.api.letsencrypt.org/directory
    dns:
        plugin: cloudflare
        api: cf
        cf_token_secret: ENC[AES256_GCM,data:2XoCgbMGnJLKmycSvIktEXHmN3ru8t98NHCLfRnJ6bjb1h0vDrBYiQ==,iv:lelWM69b43gDSRrxRmWlkbqqH1U8BEeKI+j8exAkV9g=,tag:dHjDYwn5QA+EjZ0H0ZvbhA==,type:str]
        cf_account_id_secret: ENC[AES256_GCM,data:g5EDxGD1kMpBnC47MW1VBkCJS5Eos8GmxY9+7BRgB5c=,iv:zK5Es4Q3nUAIuDS0LMjdFQ4FfD6qCvVpi8lOC+r+Bwg=,tag:9DGOQljnsNdj/cbDqXazkw==,type:str]
        cf_zone_id_secret: ENC[AES256_GCM,data:1RQfgSuM3SL5n5JrrQ88sIunIahlSbepRRHplJOfsnM=,iv:TqpCt3D6t+s5oNvQAFKTEJlr/SkejN7xiXRlKiby8fU=,tag:swbQVTh0v7aYtNQXo0xtEQ==,type:str]
gotify:
    server: https://gotify.pve.ibay.dev
    token_secret: ENC[AES256_GCM,data:+XXjJVezBRvDPUKk8Gxt,iv:lx7032U7A/Pj59CqXdriRhMsD1PzGbdynu+jz0o0nZU=,tag:sfx1BckuVeepJ+LFE4rG/Q==,type:str]
sops:
    age:
        - recipient: age15wr79l0v753jpsz0fas0xnavwqucc4sglq4mdx8dssct5g97md6qeslr6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVEl1Zmk1TmVsYWxMZmJw
            WFFsdEsrMDkrbGVFcmVFMU9zSUs3YmRpUjJrCmkveW9NbE9YNlhQMjBZcGFHWGd5
            cTltOHhxSGt1bTE5cHhkZXp0ZDl2WjAKLS0tIEpTVGJrTmlzdXNYN0xkbnJqekh1
            VDFpS1o3SlFEVkhqU3J2YzRaUURpZzgK3oMXgRWCPI7SJhfiyOcOnhg6bI+w1n9B
            Yq3XXm1T7nS3j/sQSPuU77PJYGPFvs4zCwhd62vzULlxocs1ZCMIAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T16:25:44Z"
    mac: ENC[AES256_GCM,data:rVrKITVal1sE3zBaWAH3zbQiFKp4cPyyiSJAxp9tTH+EUsc78/QdVpfzvpIPa5N3BsFW48e/puzP6TL1lNCZs8GHJyFtjt3z1in7+hivMs/Zk2Ae/L/5CkF7PkY1WN2Mc2cI65FpZs2dxhyM0SMAM+0HN2wVf1IQV1WpGRUiz10=,iv:PrO5L32etJoHws4x0P/wGZkUMe6slLlfpl6jAg7PUy8=,tag:CdlI5qAbtjSB+wWDEIU7bg==,type:str]
    encrypted_regex: ^.*(api_token|password|secret|token).*$
    version: 3.11.0
