---
all:
  children:
    proxmox:
      hosts:
        pve-rack:
          ansible_host: 192.168.1.10
        pve-mini-1:
          ansible_host: 192.168.1.11
        pve-mini-2:
          ansible_host: 192.168.1.12
        pve-mini-3:
          ansible_host: 192.168.1.13

    proxmox_mini:
      hosts:
        pve-mini-1:
        pve-mini-2:
        pve-mini-3:
