---
- name: Set timezone
  community.general.timezone:
    name: "{{ proxmox.timezone }}"

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ proxmox.base_packages }}"
    state: present
    update_cache: "true"
