---
- name: Proxmox base configuration
  hosts: proxmox
  gather_facts: true
  become: true

  pre_tasks:
    - name: Run optional backup role
      ansible.builtin.include_role:
        name: "{{ extra_role }}"
      when: extra_role is defined

  roles:
    - common
