---
# roles/access/handlers/main.yml
- name: Store OpenTofu API token on localhost
  become: false
  ansible.builtin.copy:
    dest: "{{ opentofu.token_path }}/ {{ opentofu.token_id }}.token"
    # format for bpg/proxmox provider
    content: "{{ opentofu.user }}!{{ opentofu.token_id }}={{ (token_create.stdout | from_json).value }}"
    mode: "0600"
  delegate_to: localhost
