proxmox_secrets:
    api_user: ENC[AES256_GCM,data:ozBaF2Y1Rjk=,iv:M0ezPyKUM0jy0h+prrFtH3cV8RnZ9tkcjUtXEwtnyfE=,tag:DzuJ9kxEyiyRBvb3S/mY4Q==,type:str]
    api_token_id: ENC[AES256_GCM,data:RFylfzyBnA==,iv:oECBm/s/pydMLWkxBVlJPBjcLzNgb98fxICdYv+7qz0=,tag:GZVCDXlVIN1k1njUVSJ9Qg==,type:str]
    api_token_secret: ENC[AES256_GCM,data:/Ov8gaZT+QT5lvl/segw1Dcyc53ReWw=,iv:G0+OEXO+uvzjW1ykr5p4MxqbkpAqgKeUPDTevMzudjI=,tag:56om3bRiiQsoYGL6+yVg7Q==,type:str]
sops:
    age:
        - recipient: age15wr79l0v753jpsz0fas0xnavwqucc4sglq4mdx8dssct5g97md6qeslr6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZGpBb2xqWm5SYkRBU2dM
            eVA3UStrL1BCMzB2b0NlaU1IVFpJUDc0YlhjCms5aWx1N0tIcWVNNWI5RlVuZmMv
            Z2dnTmpuVWZDZVE4NFJkcmFlOUU3L2cKLS0tIFhkYkZ2VnBPNDVuZXBTaE5tRnRT
            d2RrZ1hZcm9wTVFBZSt4bzVRTmJudHcK6o37HkPvCbL3DW8PQgjclmJVE+RryIMX
            rb85aQtTbGqkVV0qzD1GbBQr5hxleBrbGgkxXno0haCMMtLQil3tDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T11:01:12Z"
    mac: ENC[AES256_GCM,data:atXN1+NBNLDZljDgXUIo4c3xKhG9WJxqHeJudwWS9XwDdwQLhloPJK4KN8zIR6DJ8RvtPHZUEmEUzeLnQqNrkvv/ol9yaz2DbEzdc1H+Cm+q6HejJigOJIbAux7Wobidbd2T9tKBVZYw1bprqMFQYcjsXXcWOZk8X+kRghPgB5Y=,iv:stI+NLzzynelmodH06k6rC7en358FVjnmDzGMp0LJYk=,tag:UA9L+pJS8dvB5XdVo8p+8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
